/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class remoteserver_SystemControl_MediaKeys */

#ifndef _Included_remoteserver_SystemControl_MediaKeys
#define _Included_remoteserver_SystemControl_MediaKeys
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     remoteserver_SystemControl_MediaKeys
 * Method:    volumeUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_remoteserver_SystemControl_MediaKeys_volumeUp
  (JNIEnv *, jclass);

/*
 * Class:     remoteserver_SystemControl_MediaKeys
 * Method:    volumeDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_remoteserver_SystemControl_MediaKeys_volumeDown
  (JNIEnv *, jclass);

/*
 * Class:     remoteserver_SystemControl_MediaKeys
 * Method:    mute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_remoteserver_SystemControl_MediaKeys_mute
  (JNIEnv *, jclass);

/*
 * Class:     remoteserver_SystemControl_MediaKeys
 * Method:    mediaNext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_remoteserver_SystemControl_MediaKeys_mediaNext
  (JNIEnv *, jclass);

/*
 * Class:     remoteserver_SystemControl_MediaKeys
 * Method:    mediaPrevious
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_remoteserver_SystemControl_MediaKeys_mediaPrevious
  (JNIEnv *, jclass);

/*
 * Class:     remoteserver_SystemControl_MediaKeys
 * Method:    mediaPlayPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_remoteserver_SystemControl_MediaKeys_mediaPlayPause
  (JNIEnv *, jclass);

/*
 * Class:     remoteserver_SystemControl_MediaKeys
 * Method:    mediaStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_remoteserver_SystemControl_MediaKeys_mediaStop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
