/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_remoteserver_MediaKeys */

#ifndef _Included_org_remoteserver_MediaKeys
#define _Included_org_remoteserver_MediaKeys
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_remoteserver_MediaKeys
 * Method:    volumeUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_remoteserver_MediaKeys_volumeUp
  (JNIEnv *, jclass);

/*
 * Class:     org_remoteserver_MediaKeys
 * Method:    VolumeDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_remoteserver_MediaKeys_VolumeDown
  (JNIEnv *, jclass);

/*
 * Class:     org_remoteserver_MediaKeys
 * Method:    mute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_remoteserver_MediaKeys_mute
  (JNIEnv *, jclass);

/*
 * Class:     org_remoteserver_MediaKeys
 * Method:    mediaNext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_remoteserver_MediaKeys_mediaNext
  (JNIEnv *, jclass);

/*
 * Class:     org_remoteserver_MediaKeys
 * Method:    mediaPrevious
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_remoteserver_MediaKeys_mediaPrevious
  (JNIEnv *, jclass);

/*
 * Class:     org_remoteserver_MediaKeys
 * Method:    mediaPlayPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_remoteserver_MediaKeys_mediaPlayPause
  (JNIEnv *, jclass);

/*
 * Class:     org_remoteserver_MediaKeys
 * Method:    mediaStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_remoteserver_MediaKeys_mediaStop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
